spring.application.name=kairos
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/tvmaze_db}

resilience4j.circuitbreaker.instances.tvmazeService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.tvmazeService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.tvmazeService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.tvmazeService.permittedNumberOfCallsInHalfOpenState=3